version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "nathanrice"  # Update with actual GitHub username
    assignees:
      - "nathanrice"  # Update with actual GitHub username
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "transformers"
        update-types: ["version-update:semver-major"]
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "datasets"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci/cd"
      - "automated"