experiment_name: comprehensive_robustness_evaluation
description: Comprehensive evaluation with all transformation types across multiple benchmarks
mode: comprehensive

# Input configuration
benchmark_paths:
  - data/benchmarks/collected/01_logic_reasoning/easy/collected_samples.json
  - data/benchmarks/collected/01_logic_reasoning/medium/collected_samples.json
  - data/benchmarks/collected/02_mathematical_reasoning/easy/collected_samples.json
  - data/benchmarks/collected/02_mathematical_reasoning/medium/collected_samples.json
  - data/benchmarks/collected/03_puzzles_riddles/easy/collected_samples.json
  - data/benchmarks/collected/05_reading_comprehension/easy/collected_samples.json

output_dir: results

# Models to evaluate
models:
  - name: anthropic/claude-3-sonnet
    provider: openrouter
    temperature: 0.0
    max_tokens: 2048
    timeout: 90
    rate_limit: 1.0

  - name: anthropic/claude-3-haiku
    provider: openrouter
    temperature: 0.0
    max_tokens: 2048
    timeout: 60
    rate_limit: 2.0

  - name: openai/gpt-4
    provider: openrouter
    temperature: 0.0
    max_tokens: 2048
    timeout: 90
    rate_limit: 1.0

  - name: openai/gpt-3.5-turbo
    provider: openrouter
    temperature: 0.0
    max_tokens: 2048
    timeout: 60
    rate_limit: 2.0

  - name: meta-llama/llama-2-70b-chat
    provider: openrouter
    temperature: 0.0
    max_tokens: 2048
    timeout: 120
    rate_limit: 0.5

# Transformation settings
transformations:
  enabled_types:
    - all  # This will enable all available transformation types
  
  # Language settings
  languages:
    - constructed_agglutinative_1
    - constructed_agglutinative_2
    - constructed_fusional_1
    - constructed_isolating_1
  language_complexity: 6
  
  # Proper noun swap settings
  proper_noun_strategy: random
  
  # Synonym replacement settings
  synonym_rate: 0.4
  preserve_function_words: true
  
  # General settings
  seed: 123
  batch_size: 20

# Evaluation settings
max_samples: 200
sample_seed: 123
max_concurrent_requests: 5
save_interval: 50

# Analysis settings
generate_plots: true
calculate_significance: true